# ==============================================================================
# 06_Fig3_Repeated_Low_PEF_Supportive_v3_UNIFIED_FINAL.R
#
# FIGURE 3 -- SUPPORTIVE REPEATED LOW-PEF FREQUENCY ANALYSIS
#
# Manuscript:
# Cumulative low peak expiratory flow burden and severity of subsequent
# functional decline: a four-cohort longitudinal study
#
# PURPOSE
# -------
# Provide an intuitive supportive representation of the primary cumulative
# burden finding using the number of low-PEF observations across two
# assessments:
#
#   0 low-PEF observations = reference
#   1 low-PEF observation
#   2 low-PEF observations
#
# MAIN PANELS
# -----------
# A. Any limitation vs Independent
# B. Severe limitation vs Independent
# C. Severe vs Mild
#
# Each panel shows pooled categorical ORs for 0 / 1 / 2 low-PEF observations,
# with the pooled linear trend per +1 low-PEF occasion annotated below.
#
# IMPORTANT
# ---------
# - This is a SUPPORTIVE exposure representation, not the primary exposure.
# - The 0 / 1 / 2 variable is the number of low-PEF observations across two
#   assessments. It must NOT be described as a trajectory.
# - The primary manuscript exposure remains the unified continuous cumulative low-PEF burden.
#
# INPUT
# -----
# Generated by Script 31 unified-burden sensitivity analysis:
#   31J_low_count_supportive_meta.csv
# Gate:
#   31U_FINAL_UNIFIED_SENSITIVITY_GATE.csv
#
# OUTPUT DIRECTORY
# ----------------
#   output/figures
#
# OUTPUTS
# -------
#   Fig3_Repeated_Low_PEF_Supportive_v2_FINAL.pdf
#   Fig3_Repeated_Low_PEF_Supportive_v2_FINAL.tiff
#   Fig3_Repeated_Low_PEF_Supportive_v2_FINAL.png
#   Fig3_plot_data_v2_FINAL.csv
#   Fig3_caption_v2_FINAL.txt
# ==============================================================================


# ==============================================================================
# 0. CLEAN SESSION / PACKAGES
# ==============================================================================

rm(list = ls())
gc()

options(
  stringsAsFactors = FALSE,
  warn = 1,
  width = 260,
  scipen = 999
)

required_pkgs <- c(
  "data.table",
  "ggplot2"
)

missing_pkgs <- required_pkgs[
  !vapply(
    required_pkgs,
    requireNamespace,
    logical(1),
    quietly = TRUE
  )
]

if (length(missing_pkgs) > 0L) {
  stop(
    "Missing package(s): ",
    paste(
      missing_pkgs,
      collapse = ", "
    ),
    call. = FALSE
  )
}

suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
})


# ==============================================================================
# 1. PATHS
# ==============================================================================

PROJECT_ROOT <- normalizePath(".", winslash = "/", mustWork = TRUE)

UNIFIED_ROOT <- file.path(PROJECT_ROOT, "output", "compat", "unified_burden_final"
)

TABLE_DIR <- file.path(
  UNIFIED_ROOT,
  "tables"
)

QC_DIR <- file.path(
  UNIFIED_ROOT,
  "QC"
)

FIG_DIR <- file.path(
  PROJECT_ROOT,
  "output",
  "figures"
)

dir.create(
  FIG_DIR,
  recursive = TRUE,
  showWarnings = FALSE
)

INPUT_FILE <- file.path(
  TABLE_DIR,
  "31J_low_count_supportive_meta.csv"
)

GATE_FILE <- file.path(
  QC_DIR,
  "31U_FINAL_UNIFIED_SENSITIVITY_GATE.csv"
)

INPUT_FILES <- c(INPUT_FILE, GATE_FILE)
missing_files <- INPUT_FILES[!file.exists(INPUT_FILES)]

if (length(missing_files) > 0L) {
  stop(
    paste0(
      "Missing Figure 3 input file(s):\n",
      paste(missing_files, collapse = "\n"),
      "\n\nRun Script 31 (31_UNIFIED_BURDEN_COMPLETE_SENSITIVITY.R) first."
    ),
    call. = FALSE
  )
}


# ==============================================================================
# 2. SETTINGS / HELPERS
# ==============================================================================

PANEL_MAP <- data.table(
  estimand = c(
    "A_ANY_LIMITATION",
    "SEVERE_VS_INDEPENDENT",
    "SEVERE_VS_MILD"
  ),
  panel_letter = c(
    "A",
    "B",
    "C"
  ),
  panel_title = c(
    "Any limitation vs Independent",
    "Severe limitation vs Independent",
    "Severe vs Mild"
  )
)

fmt_num <- function(
  x,
  digits = 2
) {
  ifelse(
    is.na(x),
    "NA",
    formatC(
      x,
      format = "f",
      digits = digits
    )
  )
}

fmt_or_ci <- function(
  est,
  low,
  high,
  digits = 2
) {
  paste0(
    fmt_num(
      est,
      digits
    ),
    " (",
    fmt_num(
      low,
      digits
    ),
    "-",
    fmt_num(
      high,
      digits
    ),
    ")"
  )
}

fmt_p <- function(p) {
  ifelse(
    is.na(p),
    "",
    ifelse(
      p < 0.001,
      "P<0.001",
      paste0(
        "P=",
        formatC(
          p,
          format = "f",
          digits = 3
        )
      )
    )
  )
}


# ==============================================================================
# 3. READ / CHECK INPUT
# ==============================================================================

M <- fread(
  INPUT_FILE,
  encoding = "UTF-8"
)

GATE <- fread(
  GATE_FILE,
  encoding = "UTF-8"
)

if (!all(c("check", "pass", "value") %in% names(GATE))) {
  stop(
    "31U unified-sensitivity gate has unexpected columns.",
    call. = FALSE
  )
}

gate_pass <- if (is.logical(GATE$pass)) {
  GATE$pass
} else {
  tolower(trimws(as.character(GATE$pass))) %in% c(
    "true", "t", "1", "yes"
  )
}

if (!all(gate_pass)) {
  cat("\nScript 31 final sensitivity gate:\n")
  print(GATE)
  stop(
    "Script 31 unified sensitivity gate did not fully pass. Figure 3 generation stopped.",
    call. = FALSE
  )
}

required_cols <- c(
  "estimand",
  "exposure_spec",
  "contrast",
  "pooled_OR",
  "CI_low_mKH",
  "CI_high_mKH",
  "P_mKH",
  "I2"
)

missing_cols <- setdiff(
  required_cols,
  names(M)
)

if (length(missing_cols) > 0L) {
  stop(
    "31J_low_count_supportive_meta.csv is missing column(s): ",
    paste(
      missing_cols,
      collapse = ", "
    ),
    call. = FALSE
  )
}


# ==============================================================================
# 4. FROZEN QC TARGETS
# ==============================================================================

EXPECTED <- data.table(
  estimand = c(
    "A_ANY_LIMITATION",
    "A_ANY_LIMITATION",
    "A_ANY_LIMITATION",
    "SEVERE_VS_INDEPENDENT",
    "SEVERE_VS_INDEPENDENT",
    "SEVERE_VS_INDEPENDENT",
    "SEVERE_VS_MILD",
    "SEVERE_VS_MILD",
    "SEVERE_VS_MILD"
  ),
  contrast = c(
    "1 vs 0",
    "2 vs 0",
    "per +1 low occasion",
    "1 vs 0",
    "2 vs 0",
    "per +1 low occasion",
    "1 vs 0",
    "2 vs 0",
    "per +1 low occasion"
  ),
  expected_OR = c(
    1.251900,
    1.542527,
    1.245733,
    1.488079,
    2.035399,
    1.441822,
    1.344283,
    1.562512,
    1.280396
  )
)

QC_TOL <- 5e-4

obs_qc <- M[
  estimand %in%
    PANEL_MAP$estimand &
  contrast %in%
    EXPECTED$contrast,
  .(
    estimand,
    contrast,
    observed_OR = pooled_OR
  )
]

QC <- merge(
  EXPECTED,
  obs_qc,
  by = c(
    "estimand",
    "contrast"
  ),
  all.x = TRUE
)

QC[
  ,
  abs_difference :=
    abs(
      observed_OR -
      expected_OR
    )
]

QC[
  ,
  pass :=
    abs_difference <=
      QC_TOL
]

cat("\n")
cat("======================================================================\n")
cat("FIGURE 3 INPUT QC\n")
cat("======================================================================\n")
print(QC)

if (!all(QC$pass)) {
  stop(
    "Figure 3 input results do not match the locked supportive analysis.",
    call. = FALSE
  )
}


# ==============================================================================
# 5. BUILD CATEGORICAL 0 / 1 / 2 DATA
# ==============================================================================

CAT <- M[
  estimand %in%
    PANEL_MAP$estimand &
  exposure_spec ==
    "CATEGORICAL_0_1_2" &
  contrast %in%
    c(
      "1 vs 0",
      "2 vs 0"
    ),
  .(
    estimand,
    contrast,
    OR = pooled_OR,
    CI_low = CI_low_mKH,
    CI_high = CI_high_mKH,
    P = P_mKH,
    I2
  )
]

# Add reference category explicitly.
REF <- unique(
  CAT[
    ,
    .(
      estimand
    )
  ]
)

REF[
  ,
  `:=`(
    contrast = "0 reference",
    OR = 1,
    CI_low = 1,
    CI_high = 1,
    P = NA_real_,
    I2 = NA_real_
  )
]

CAT <- rbindlist(
  list(
    REF,
    CAT
  ),
  fill = TRUE
)

CAT[
  ,
  low_count := fifelse(
    contrast ==
      "0 reference",
    0L,
    fifelse(
      contrast ==
        "1 vs 0",
      1L,
      2L
    )
  )
]

CAT <- merge(
  CAT,
  PANEL_MAP,
  by = "estimand",
  all.x = TRUE,
  sort = FALSE
)

CAT[
  ,
  panel := factor(
    paste0(
      panel_letter,
      "  ",
      panel_title
    ),
    levels = paste0(
      PANEL_MAP$panel_letter,
      "  ",
      PANEL_MAP$panel_title
    )
  )
]

CAT[
  ,
  point_label := fifelse(
    low_count ==
      0L,
    "Reference",
    fmt_or_ci(
      OR,
      CI_low,
      CI_high,
      digits = 2
    )
  )
]


# ==============================================================================
# 6. BUILD LINEAR TREND ANNOTATIONS
# ==============================================================================

TREND <- M[
  estimand %in%
    PANEL_MAP$estimand &
  exposure_spec ==
    "TREND_PER_1_LOW_OCCASION" &
  contrast ==
    "per +1 low occasion",
  .(
    estimand,
    trend_OR = pooled_OR,
    trend_CI_low = CI_low_mKH,
    trend_CI_high = CI_high_mKH,
    trend_P = P_mKH,
    trend_I2 = I2
  )
]

TREND <- merge(
  TREND,
  PANEL_MAP,
  by = "estimand",
  all.x = TRUE,
  sort = FALSE
)

TREND[
  ,
  panel := factor(
    paste0(
      panel_letter,
      "  ",
      panel_title
    ),
    levels = paste0(
      PANEL_MAP$panel_letter,
      "  ",
      PANEL_MAP$panel_title
    )
  )
]

TREND[
  ,
  trend_label := paste0(
    "Per +1 low-PEF occasion: OR ",
    fmt_or_ci(
      trend_OR,
      trend_CI_low,
      trend_CI_high,
      digits = 2
    ),
    "; ",
    fmt_p(
      trend_P
    ),
    "; I²=",
    fmt_num(
      trend_I2,
      1
    ),
    "%"
  )
]


# ==============================================================================
# 7. SAVE PLOT DATA
# ==============================================================================

plot_export <- merge(
  CAT,
  TREND[
    ,
    .(
      estimand,
      trend_OR,
      trend_CI_low,
      trend_CI_high,
      trend_P,
      trend_I2,
      trend_label
    )
  ],
  by = "estimand",
  all.x = TRUE
)

fwrite(
  plot_export,
  file.path(
    FIG_DIR,
    "Fig3_plot_data_v3_UNIFIED_FINAL.csv"
  ),
  bom = TRUE
)


# ==============================================================================
# 8. VISUAL SETTINGS
# ==============================================================================

BASE_FAMILY <- "Arial"

COL_MAIN <- "#2E628A"
COL_LINE <- "#7EA1BA"
COL_REF  <- "#7E8790"
COL_TEXT <- "#17212B"
COL_LIGHT <- "#647383"
COL_GRID <- "#E3E8ED"

# Keep a common y-axis across panels so that severity differences are visually
# comparable.
Y_MAX <- max(
  CAT$CI_high[
    CAT$low_count > 0
  ],
  na.rm = TRUE
)

Y_MAX <- max(
  2.25,
  ceiling(
    Y_MAX * 10
  ) /
    10 +
    0.10
)

# Position text above categorical points.
CAT[
  ,
  label_y := pmin(
    CI_high +
      0.10,
    Y_MAX -
      0.06
  )
]

# Trend annotation at the bottom of each panel to avoid competing with
# the categorical 0/1/2 effect labels.
TREND[
  ,
  trend_y := 0.885
]


# ==============================================================================
# 9. BUILD FIGURE
# ==============================================================================

p <- ggplot(
  CAT,
  aes(
    x = low_count,
    y = OR
  )
) +
  geom_hline(
    yintercept = 1,
    linetype = "dashed",
    linewidth = 0.55,
    colour = "#777777"
  ) +
  geom_line(
    aes(
      group = estimand
    ),
    linewidth = 0.95,
    colour = COL_LINE
  ) +
  geom_errorbar(
    data = CAT[
      low_count > 0
    ],
    aes(
      ymin = CI_low,
      ymax = CI_high
    ),
    width = 0.08,
    linewidth = 0.80,
    colour = COL_MAIN
  ) +
  geom_point(
    data = CAT[
      low_count ==
        0
    ],
    shape = 21,
    size = 3.5,
    stroke = 1.0,
    fill = "white",
    colour = COL_REF
  ) +
  geom_point(
    data = CAT[
      low_count > 0
    ],
    shape = 21,
    size = 4.0,
    stroke = 1.05,
    fill = "white",
    colour = COL_MAIN
  ) +
  geom_text(
    data = CAT[
      low_count ==
        0
    ],
    aes(
      y = 1.08,
      label = "Reference"
    ),
    family = BASE_FAMILY,
    size = 3.0,
    colour = COL_LIGHT
  ) +
  geom_text(
    data = CAT[
      low_count == 1
    ],
    aes(
      y = label_y,
      label = point_label
    ),
    family = BASE_FAMILY,
    size = 3.05,
    colour = COL_TEXT,
    hjust = 0.5
  ) +
  geom_text(
    data = CAT[
      low_count == 2
    ],
    aes(
      x = 1.97,
      y = label_y,
      label = point_label
    ),
    inherit.aes = FALSE,
    family = BASE_FAMILY,
    size = 3.05,
    colour = COL_TEXT,
    hjust = 1
  ) +
  geom_text(
    data = TREND,
    aes(
      x = 0.03,
      y = trend_y,
      label = trend_label
    ),
    inherit.aes = FALSE,
    hjust = 0,
    vjust = 0,
    family = BASE_FAMILY,
    size = 2.85,
    colour = COL_LIGHT
  ) +
  facet_wrap(
    ~ panel,
    nrow = 1
  ) +
  scale_x_continuous(
    breaks = c(
      0,
      1,
      2
    ),
    labels = c(
      "0",
      "1",
      "2"
    ),
    limits = c(
      -0.10,
      2.10
    )
  ) +
  scale_y_continuous(
    limits = c(
      0.85,
      Y_MAX
    ),
    breaks = seq(
      1.0,
      Y_MAX,
      by = 0.25
    ),
    expand = expansion(
      mult = c(
        0,
        0
      )
    )
  ) +
  labs(
    title = "Figure 3. Frequency of low-PEF observations and functional outcomes",
    subtitle = paste0(
      "Supportive pooled analysis across two PEF assessments; 0 = neither, 1 = one, and 2 = both assessments. ",
      "The unified continuous cumulative low-PEF burden remains the primary exposure."
    ),
    x = "Number of low-PEF observations across two assessments",
    y = "Odds ratio (95% CI)"
  ) +
  theme_minimal(
    base_family = BASE_FAMILY,
    base_size = 11.5
  ) +
  theme(
    plot.title = element_text(
      face = "bold",
      size = 14.5,
      colour = COL_TEXT,
      hjust = 0
    ),
    plot.subtitle = element_text(
      size = 10.2,
      colour = COL_LIGHT,
      margin = margin(
        b = 8
      )
    ),
    strip.text = element_text(
      face = "bold",
      size = 10.8,
      colour = COL_TEXT,
      hjust = 0
    ),
    strip.background = element_rect(
      fill = "#F2F5F8",
      colour = "#CDD5DC",
      linewidth = 0.7
    ),
    axis.title.x = element_text(
      face = "bold",
      size = 10.5,
      colour = COL_TEXT,
      margin = margin(
        t = 8
      )
    ),
    axis.title.y = element_text(
      face = "bold",
      size = 10.5,
      colour = COL_TEXT,
      margin = margin(
        r = 8
      )
    ),
    axis.text.x = element_text(
      face = "bold",
      size = 10.2,
      colour = COL_TEXT
    ),
    axis.text.y = element_text(
      size = 9.5,
      colour = COL_TEXT
    ),
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(
      colour = COL_GRID,
      linewidth = 0.45
    ),
    panel.border = element_rect(
      fill = NA,
      colour = "#CDD5DC",
      linewidth = 0.7
    ),
    panel.spacing.x = unit(
      0.8,
      "lines"
    ),
    plot.margin = margin(
      10,
      12,
      10,
      10
    )
  )


# ==============================================================================
# 10. EXPORT FIGURE
# ==============================================================================

OUT_PNG <- file.path(
  FIG_DIR,
  "Fig3_Repeated_Low_PEF_Supportive_v2_FINAL.png"
)

OUT_PDF <- file.path(
  FIG_DIR,
  "Fig3_Repeated_Low_PEF_Supportive_v2_FINAL.pdf"
)

OUT_TIFF <- file.path(
  FIG_DIR,
  "Fig3_Repeated_Low_PEF_Supportive_v2_FINAL.tiff"
)

plot_width <- 14.2
plot_height <- 6.6

ggsave(
  filename = OUT_PNG,
  plot = p,
  width = plot_width,
  height = plot_height,
  units = "in",
  dpi = 320,
  bg = "white"
)

ggsave(
  filename = OUT_PDF,
  plot = p,
  width = plot_width,
  height = plot_height,
  units = "in",
  device = cairo_pdf,
  bg = "white"
)

ggsave(
  filename = OUT_TIFF,
  plot = p,
  width = plot_width,
  height = plot_height,
  units = "in",
  dpi = 600,
  compression = "lzw",
  bg = "white"
)


# ==============================================================================
# 11. CAPTION
# ==============================================================================

caption_txt <- paste(
  "Figure 3. Supportive analysis according to the frequency of low peak expiratory flow observations across two assessments.",
  "Pooled random-effects odds ratios (95% confidence intervals) are shown for one and two low-PEF observations relative to no low-PEF observations.",
  "Panel A shows any subsequent functional limitation versus remaining independent, Panel B shows severe limitation versus remaining independent, and Panel C shows the formal severe-versus-mild contrast.",
  "The annotation in each panel reports the pooled linear trend per additional low-PEF occasion.",
  "The 0/1/2 exposure represents the number of low-PEF observations across two assessments and is a supportive exposure representation rather than a trajectory.",
  "This supportive analysis accompanies the primary unified continuous burden, defined from the mean of two max(0, -residual z) deficits and standardized within cohort.",
  "Pooled estimates use REML random-effects meta-analysis with modified Hartung-Knapp inference.",
  sep = " "
)

writeLines(
  caption_txt,
  con = file.path(
    FIG_DIR,
    "Fig3_caption_v3_UNIFIED_FINAL.txt"
  ),
  useBytes = TRUE
)


# ==============================================================================
# 12. CONSOLE DASHBOARD
# ==============================================================================

cat("\n")
cat("======================================================================\n")
cat("FIGURE 3 UNIFIED-SENSITIVITY FINAL COMPLETED\n")
cat("======================================================================\n")

cat("\n[1] SCRIPT 31 FINAL SENSITIVITY GATE\n\n")
print(GATE)

cat("\n[2] CATEGORICAL 0/1/2 POOLED ESTIMATES\n\n")
print(
  CAT[
    ,
    .(
      panel_title,
      low_count,
      OR,
      CI_low,
      CI_high,
      P
    )
  ]
)

cat("\n[3] LINEAR TREND PER +1 LOW-PEF OCCASION\n\n")
print(
  TREND[
    ,
    .(
      panel_title,
      trend_OR,
      trend_CI_low,
      trend_CI_high,
      trend_P,
      trend_I2
    )
  ]
)

cat("\n[4] OUTPUT FILES\n\n")
cat("  ", OUT_PNG, "\n", sep = "")
cat("  ", OUT_PDF, "\n", sep = "")
cat("  ", OUT_TIFF, "\n", sep = "")
cat(
  "  ",
  file.path(
    FIG_DIR,
    "Fig3_plot_data_v3_UNIFIED_FINAL.csv"
  ),
  "\n",
  sep = ""
)
cat(
  "  ",
  file.path(
    FIG_DIR,
    "Fig3_caption_v3_UNIFIED_FINAL.txt"
  ),
  "\n",
  sep = ""
)

cat("\nREADING RULE\n")
cat("- Source: Script 31 unified-burden sensitivity analysis.\n")
cat("- This is supportive evidence, not a replacement for the unified continuous-burden primary analysis.\n")
cat("- 0 / 1 / 2 = number of low-PEF observations across two assessments.\n")
cat("- Do not describe these categories as a trajectory.\n")

cat("\nFINAL STATUS: PASS\n")
cat("======================================================================\n")
