# ==============================================================================
# 09_FigS3_Alternative_Outcome_Robustness_v2_UNIFIED_FINAL.R
#
# Supplementary Figure S3
# Alternative severe / stricter functional outcome definitions
#
# PURPOSE
# -------
# Display cohort-specific and pooled associations for two prespecified
# sensitivity outcomes using the unified continuous cumulative low-PEF burden exposure:
#
#   Panel A. Severe functional limitation vs all non-severe destinations
#   Panel B. Strict deterioration: increase of >=2 ADL/IADL limitations
#
# Both panels show ORs per +1 SD unified cumulative low-PEF burden.
#
# REQUIRED UPSTREAM FILES
# -----------------------
# Generated by Script 31 unified-burden sensitivity analysis:
#
#   31K_severe_vs_nonsevere_results.csv
#   31L_severe_vs_nonsevere_meta.csv
#   31R_ge2_deterioration_results.csv
#   31S_ge2_deterioration_meta.csv
#   31U_FINAL_UNIFIED_SENSITIVITY_GATE.csv
#
# OUTPUTS
# -------
#   FigS3_Alternative_Outcome_Robustness_FINAL.png
#   FigS3_Alternative_Outcome_Robustness_FINAL.pdf
#   FigS3_Alternative_Outcome_Robustness_FINAL.tiff
#   FigS3_Alternative_Outcome_Robustness_plot_data.csv
#   FigS3_caption_FINAL.txt
# ==============================================================================


# ==============================================================================
# 0. CLEAN SESSION / PACKAGES
# ==============================================================================

rm(list = ls())
gc()

options(
  stringsAsFactors = FALSE,
  warn = 1,
  width = 220,
  scipen = 999
)

required_pkgs <- c(
  "data.table",
  "ggplot2"
)

missing_pkgs <- required_pkgs[
  !vapply(
    required_pkgs,
    requireNamespace,
    logical(1),
    quietly = TRUE
  )
]

if (length(missing_pkgs) > 0L) {
  stop(
    "Missing package(s): ",
    paste(missing_pkgs, collapse = ", "),
    call. = FALSE
  )
}

suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
})


# ==============================================================================
# 1. PATHS
# ==============================================================================

PROJECT_ROOT <- normalizePath(".", winslash = "/", mustWork = TRUE)

UNIFIED_ROOT <- file.path(PROJECT_ROOT, "output", "compat", "unified_burden_final"
)

TABLE_DIR <- file.path(
  UNIFIED_ROOT,
  "tables"
)

QC_DIR <- file.path(
  UNIFIED_ROOT,
  "QC"
)

FIG_DIR <- file.path(
  PROJECT_ROOT,
  "output",
  "figures"
)

dir.create(
  FIG_DIR,
  recursive = TRUE,
  showWarnings = FALSE
)

FILE_SEVERE_RESULTS <- file.path(
  TABLE_DIR,
  "31K_severe_vs_nonsevere_results.csv"
)

FILE_SEVERE_META <- file.path(
  TABLE_DIR,
  "31L_severe_vs_nonsevere_meta.csv"
)

FILE_GE2_RESULTS <- file.path(
  TABLE_DIR,
  "31R_ge2_deterioration_results.csv"
)

FILE_GE2_META <- file.path(
  TABLE_DIR,
  "31S_ge2_deterioration_meta.csv"
)

FILE_GATE <- file.path(
  QC_DIR,
  "31U_FINAL_UNIFIED_SENSITIVITY_GATE.csv"
)

input_files <- c(
  FILE_SEVERE_RESULTS,
  FILE_SEVERE_META,
  FILE_GE2_RESULTS,
  FILE_GE2_META,
  FILE_GATE
)

missing_files <- input_files[
  !file.exists(input_files)
]

if (length(missing_files) > 0L) {
  stop(
    paste0(
      "Missing required input file(s):\n",
      paste(missing_files, collapse = "\n"),
      "\n\nRun Script 31 (31_UNIFIED_BURDEN_COMPLETE_SENSITIVITY.R) first."
    ),
    call. = FALSE
  )
}


# ==============================================================================
# 2. HELPERS
# ==============================================================================

pick_col <- function(dt, candidates) {
  hit <- candidates[
    candidates %in% names(dt)
  ]

  if (length(hit) == 0L) {
    return(NULL)
  }

  hit[1]
}


standardize_cohort_results <- function(dt) {

  dt <- as.data.table(copy(dt))

  or_col <- pick_col(
    dt,
    c(
      "OR",
      "effect",
      "estimate"
    )
  )

  low_col <- pick_col(
    dt,
    c(
      "CI_low",
      "CI_low_95",
      "lower",
      "lower_CI"
    )
  )

  high_col <- pick_col(
    dt,
    c(
      "CI_high",
      "CI_high_95",
      "upper",
      "upper_CI"
    )
  )

  if (
    is.null(or_col) ||
    is.null(low_col) ||
    is.null(high_col)
  ) {
    stop(
      "Could not identify OR / CI columns in cohort-level result file.",
      call. = FALSE
    )
  }

  dt[
    ,
    `:=`(
      effect_std = as.numeric(
        get(or_col)
      ),
      low_std = as.numeric(
        get(low_col)
      ),
      high_std = as.numeric(
        get(high_col)
      )
    )
  ]

  dt
}


standardize_meta_results <- function(dt) {

  dt <- as.data.table(copy(dt))

  or_col <- pick_col(
    dt,
    c(
      "pooled_OR",
      "pooled_effect",
      "OR",
      "effect"
    )
  )

  low_col <- pick_col(
    dt,
    c(
      "CI_low_mKH",
      "CI_low",
      "lower",
      "lower_CI"
    )
  )

  high_col <- pick_col(
    dt,
    c(
      "CI_high_mKH",
      "CI_high",
      "upper",
      "upper_CI"
    )
  )

  i2_col <- pick_col(
    dt,
    c(
      "I2",
      "I2_pct",
      "I2_percent"
    )
  )

  if (
    is.null(or_col) ||
    is.null(low_col) ||
    is.null(high_col)
  ) {
    stop(
      "Could not identify pooled OR / CI columns in meta-analysis file.",
      call. = FALSE
    )
  }

  dt[
    ,
    `:=`(
      effect_std = as.numeric(
        get(or_col)
      ),
      low_std = as.numeric(
        get(low_col)
      ),
      high_std = as.numeric(
        get(high_col)
      ),
      I2_std = if (
        !is.null(i2_col)
      ) {
        as.numeric(
          get(i2_col)
        )
      } else {
        NA_real_
      }
    )
  ]

  dt
}


fmt_or_ci <- function(
  est,
  low,
  high
) {
  paste0(
    sprintf("%.2f", est),
    " (",
    sprintf("%.2f", low),
    "-",
    sprintf("%.2f", high),
    ")"
  )
}


fmt_i2 <- function(x) {
  ifelse(
    is.na(x),
    "",
    paste0(
      "I",
      intToUtf8(178),
      "=",
      sprintf("%.1f", x),
      "%"
    )
  )
}


# ==============================================================================
# 3. READ INPUTS
# ==============================================================================

severe_results <- standardize_cohort_results(
  fread(
    FILE_SEVERE_RESULTS,
    encoding = "UTF-8"
  )
)

severe_meta <- standardize_meta_results(
  fread(
    FILE_SEVERE_META,
    encoding = "UTF-8"
  )
)

ge2_results <- standardize_cohort_results(
  fread(
    FILE_GE2_RESULTS,
    encoding = "UTF-8"
  )
)

ge2_meta <- standardize_meta_results(
  fread(
    FILE_GE2_META,
    encoding = "UTF-8"
  )
)

GATE <- as.data.table(
  fread(
    FILE_GATE,
    encoding = "UTF-8"
  )
)

if (!all(c("check", "pass", "value") %in% names(GATE))) {
  stop(
    "31U unified-sensitivity gate has unexpected columns.",
    call. = FALSE
  )
}

gate_pass <- if (is.logical(GATE$pass)) {
  GATE$pass
} else {
  tolower(trimws(as.character(GATE$pass))) %in%
    c("true", "t", "1", "yes")
}

if (!all(gate_pass)) {
  cat("\nScript 31 final sensitivity gate:\n")
  print(GATE)
  stop(
    "Script 31 unified sensitivity gate did not fully pass. FigS3 generation stopped.",
    call. = FALSE
  )
}


# ==============================================================================
# 4. SELECT THE LOCKED CONTINUOUS-BURDEN ANALYSES
# ==============================================================================

# Panel A: Severe vs all non-severe, continuous cumulative burden only.
if (!"analysis" %in% names(severe_results)) {
  stop(
    "31K_severe_vs_nonsevere_results.csv does not contain 'analysis'.",
    call. = FALSE
  )
}

severe_cohort <- severe_results[
  analysis ==
    "Continuous cumulative burden per +1 SD"
]

if (nrow(severe_cohort) == 0L) {
  stop(
    "Continuous severe-vs-nonsevere cohort results were not found.",
    call. = FALSE
  )
}

# Meta file uses 'exposure' for this module.
if (!"exposure" %in% names(severe_meta)) {
  stop(
    "31L_severe_vs_nonsevere_meta.csv does not contain 'exposure'.",
    call. = FALSE
  )
}

severe_pool <- severe_meta[
  exposure ==
    "Continuous cumulative burden per +1 SD"
]

if (nrow(severe_pool) != 1L) {
  stop(
    "Expected exactly one pooled continuous severe-vs-nonsevere row.",
    call. = FALSE
  )
}


# Panel B: strict >=2 ADL/IADL-item deterioration.
if (
  "analysis" %in% names(ge2_results)
) {
  ge2_cohort <- ge2_results[
    analysis ==
      "STRICT_GE2_ITEM_DETERIORATION"
  ]
} else {
  ge2_cohort <- copy(
    ge2_results
  )
}

if (nrow(ge2_cohort) == 0L) {
  stop(
    "Strict >=2-item deterioration cohort results were not found.",
    call. = FALSE
  )
}

if (
  "analysis" %in% names(ge2_meta)
) {
  ge2_pool <- ge2_meta[
    analysis ==
      "STRICT_GE2_ITEM_DETERIORATION"
  ]
} else {
  ge2_pool <- copy(
    ge2_meta
  )
}

if (nrow(ge2_pool) != 1L) {
  stop(
    "Expected exactly one pooled strict >=2-item deterioration row.",
    call. = FALSE
  )
}


# ==============================================================================
# 5. FROZEN QC -- SCRIPT 31 UNIFIED BURDEN
# ==============================================================================

QC_TOL <- 5e-4

EXPECTED_COHORTS <- c(
  "HRS",
  "ELSA",
  "SHARE",
  "CHARLS"
)

# Locked Script 31 cohort-specific ORs for the continuous unified burden.
expected_severe <- data.table(
  cohort = EXPECTED_COHORTS,
  expected_OR = c(
    1.288778,
    1.218811,
    1.309144,
    1.203216
  )
)

expected_ge2 <- data.table(
  cohort = EXPECTED_COHORTS,
  expected_OR = c(
    1.263740,
    1.247733,
    1.375226,
    1.197061
  )
)

build_cohort_qc <- function(
  observed_dt,
  expected_dt
) {

  z <- merge(
    observed_dt[
      ,
      .(
        cohort,
        observed_OR = effect_std
      )
    ],
    expected_dt,
    by = "cohort",
    all.y = TRUE
  )

  z[
    ,
    abs_difference :=
      abs(
        observed_OR -
          expected_OR
      )
  ]

  z[
    ,
    pass :=
      !is.na(observed_OR) &
      abs_difference <= QC_TOL
  ]

  z[]
}

severe_qc <- build_cohort_qc(
  severe_cohort,
  expected_severe
)

ge2_qc <- build_cohort_qc(
  ge2_cohort,
  expected_ge2
)

# Locked Script 31 pooled ORs.
meta_qc <- data.table(
  analysis = c(
    "Severe vs all non-severe",
    "Strict >=2-item deterioration"
  ),
  observed_OR = c(
    severe_pool$effect_std[1],
    ge2_pool$effect_std[1]
  ),
  expected_OR = c(
    1.257469,
    1.273087
  )
)

meta_qc[
  ,
  abs_difference :=
    abs(
      observed_OR -
        expected_OR
    )
]

meta_qc[
  ,
  pass :=
    !is.na(observed_OR) &
    abs_difference <= QC_TOL
]

cat("\n")
cat("======================================================================\n")
cat("FIGURE S3 UNIFIED-BURDEN INPUT QC\n")
cat("======================================================================\n")

cat("\nScript 31 final sensitivity gate:\n")
print(GATE)

cat("\nSevere-vs-nonsevere cohort-specific frozen checks:\n")
print(
  severe_qc
)

cat("\nStrict >=2-item cohort-specific frozen checks:\n")
print(
  ge2_qc
)

cat("\nPooled frozen checks:\n")
print(
  meta_qc
)

if (
  !all(severe_qc$pass) ||
  !all(ge2_qc$pass) ||
  !all(meta_qc$pass)
) {
  stop(
    "Figure S3 input results do not match the locked Script 31 unified analyses.",
    call. = FALSE
  )
}


# ==============================================================================
# 6. BUILD PLOT DATA
# ==============================================================================

COHORT_LEVELS <- c(
  "HRS",
  "ELSA",
  "SHARE",
  "CHARLS",
  "Pooled"
)

PANEL_A <- "A  Severe limitation vs all non-severe destinations"
PANEL_B <- "B  Strict deterioration: >=2 ADL/IADL limitations"

a_cohort <- severe_cohort[
  ,
  .(
    cohort,
    effect = effect_std,
    CI_low = low_std,
    CI_high = high_std,
    I2 = NA_real_,
    row_type = "Cohort",
    panel = PANEL_A
  )
]

a_pool <- data.table(
  cohort = "Pooled",
  effect = severe_pool$effect_std[1],
  CI_low = severe_pool$low_std[1],
  CI_high = severe_pool$high_std[1],
  I2 = severe_pool$I2_std[1],
  row_type = "Pooled",
  panel = PANEL_A
)

b_cohort <- ge2_cohort[
  ,
  .(
    cohort,
    effect = effect_std,
    CI_low = low_std,
    CI_high = high_std,
    I2 = NA_real_,
    row_type = "Cohort",
    panel = PANEL_B
  )
]

b_pool <- data.table(
  cohort = "Pooled",
  effect = ge2_pool$effect_std[1],
  CI_low = ge2_pool$low_std[1],
  CI_high = ge2_pool$high_std[1],
  I2 = ge2_pool$I2_std[1],
  row_type = "Pooled",
  panel = PANEL_B
)

plot_dt <- rbindlist(
  list(
    a_cohort,
    a_pool,
    b_cohort,
    b_pool
  ),
  use.names = TRUE,
  fill = TRUE
)

plot_dt[
  ,
  cohort := factor(
    cohort,
    levels = rev(
      COHORT_LEVELS
    )
  )
]

plot_dt[
  ,
  panel := factor(
    panel,
    levels = c(
      PANEL_A,
      PANEL_B
    )
  )
]

plot_dt[
  ,
  estimate_text :=
    fmt_or_ci(
      effect,
      CI_low,
      CI_high
    )
]

plot_dt[
  ,
  stat_text :=
    fifelse(
      row_type ==
        "Pooled",
      paste0(
        estimate_text,
        "; ",
        fmt_i2(
          I2
        )
      ),
      estimate_text
    )
]


# ==============================================================================
# 7. SAVE MACHINE-READABLE PLOT DATA
# ==============================================================================

OUT_DATA <- file.path(
  FIG_DIR,
  "FigS3_Alternative_Outcome_Robustness_plot_data_UNIFIED_FINAL.csv"
)

fwrite(
  plot_dt,
  OUT_DATA,
  bom = TRUE
)


# ==============================================================================
# 8. VISUAL SETTINGS
# ==============================================================================

COL_MAIN <- "#2F6DA3"
COL_POOL <- "#1D4F78"
COL_TEXT <- "#263544"
COL_SUBTLE <- "#647383"
COL_GRID <- "#D5DBE3"

x_min <- min(
  c(
    0.95,
    plot_dt$CI_low
  ),
  na.rm = TRUE
)

x_max_effect <- max(
  plot_dt$CI_high,
  na.rm = TRUE
)

text_x <- x_max_effect +
  0.12

x_upper <- text_x +
  0.15


# ==============================================================================
# 9. DRAW FIGURE
# ==============================================================================

p <- ggplot(
  plot_dt,
  aes(
    x = effect,
    y = cohort
  )
) +
  facet_wrap(
    ~ panel,
    ncol = 1,
    scales = "fixed"
  ) +
  geom_vline(
    xintercept = 1,
    linetype = "dashed",
    linewidth = 0.48,
    colour = "#777777"
  ) +
  geom_errorbarh(
    aes(
      xmin = CI_low,
      xmax = CI_high
    ),
    height = 0.16,
    linewidth = 0.90,
    colour = COL_MAIN
  ) +
  geom_point(
    data = plot_dt[
      row_type ==
        "Cohort"
    ],
    shape = 21,
    size = 3.4,
    stroke = 1.05,
    fill = "white",
    colour = COL_MAIN
  ) +
  geom_point(
    data = plot_dt[
      row_type ==
        "Pooled"
    ],
    shape = 23,
    size = 4.3,
    stroke = 1.05,
    fill = COL_POOL,
    colour = COL_POOL
  ) +
  geom_text(
    aes(
      x = text_x,
      label = stat_text
    ),
    hjust = 0,
    size = 3.55,
    colour = "#333333"
  ) +
  scale_x_continuous(
    limits = c(
      x_min,
      x_upper
    ),
    breaks = pretty(
      c(
        x_min,
        x_max_effect
      ),
      n = 6
    ),
    expand = expansion(
      mult = c(
        0.01,
        0.01
      )
    )
  ) +
  labs(
    title = "Supplementary Figure S3. Alternative functional outcome definitions",
    subtitle = paste0(
      "Cohort-specific and pooled ORs per +1 SD unified cumulative low-PEF burden. ",
      "Both analyses are sensitivity outcomes rather than co-primary endpoints."
    ),
    x = "Odds ratio (95% CI)",
    y = NULL,
    caption = paste0(
      "Diamond = pooled REML estimate with modified Hartung-Knapp inference; ",
      "hollow circles = cohort-specific estimates. ",
      "I² is shown for pooled estimates."
    )
  ) +
  theme_minimal(
    base_size = 12
  ) +
  theme(
    plot.title = element_text(
      face = "bold",
      size = 16,
      colour = COL_TEXT
    ),
    plot.subtitle = element_text(
      size = 11,
      colour = COL_SUBTLE,
      margin = margin(
        b = 8
      )
    ),
    plot.caption = element_text(
      size = 10,
      colour = COL_SUBTLE,
      hjust = 0
    ),
    axis.title.x = element_text(
      face = "bold",
      size = 12,
      colour = COL_TEXT
    ),
    axis.text.x = element_text(
      size = 10,
      colour = COL_TEXT
    ),
    axis.text.y = element_text(
      face = "bold",
      size = 11,
      colour = COL_TEXT
    ),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(
      colour = COL_GRID,
      linewidth = 0.45
    ),
    strip.text = element_text(
      face = "bold",
      size = 12,
      colour = COL_TEXT
    ),
    strip.background = element_rect(
      fill = "#EEF2F6",
      colour = "#C9D2DC",
      linewidth = 0.8
    ),
    panel.spacing = unit(
      1.2,
      "lines"
    ),
    plot.margin = margin(
      14,
      150,
      12,
      12
    )
  ) +
  coord_cartesian(
    clip = "off"
  )


# ==============================================================================
# 10. EXPORT
# ==============================================================================

OUT_PNG <- file.path(
  FIG_DIR,
  "FigS3_Alternative_Outcome_Robustness_FINAL.png"
)

OUT_PDF <- file.path(
  FIG_DIR,
  "FigS3_Alternative_Outcome_Robustness_FINAL.pdf"
)

OUT_TIFF <- file.path(
  FIG_DIR,
  "FigS3_Alternative_Outcome_Robustness_FINAL.tiff"
)

ggsave(
  filename = OUT_PNG,
  plot = p,
  width = 12.5,
  height = 8.4,
  units = "in",
  dpi = 320,
  bg = "white"
)

ggsave(
  filename = OUT_PDF,
  plot = p,
  width = 12.5,
  height = 8.4,
  units = "in",
  device = cairo_pdf,
  bg = "white"
)

ggsave(
  filename = OUT_TIFF,
  plot = p,
  width = 12.5,
  height = 8.4,
  units = "in",
  dpi = 600,
  compression = "lzw",
  bg = "white"
)


# ==============================================================================
# 11. CAPTION
# ==============================================================================

caption_txt <- paste(
  "Supplementary Figure S3. Alternative functional outcome definitions.",
  "Associations are shown per 1-standard-deviation increase in the unified cumulative low peak expiratory flow burden.",
  "The unified burden was based on the mean of two max(0, -residual z) deficits and standardized within cohort.",
  "Panel A defines the outcome as severe functional limitation versus all non-severe destinations.",
  "Panel B uses a stricter deterioration endpoint defined as an increase of at least two ADL/IADL limitations.",
  "Hollow circles show cohort-specific estimates and diamonds show pooled random-effects estimates.",
  "Pooled analyses use REML estimation with modified Hartung-Knapp inference.",
  "These analyses are sensitivity outcomes and are not co-primary endpoints.",
  sep = " "
)

OUT_CAPTION <- file.path(
  FIG_DIR,
  "FigS3_caption_UNIFIED_FINAL.txt"
)

writeLines(
  caption_txt,
  con = OUT_CAPTION,
  useBytes = TRUE
)


# ==============================================================================
# 12. CONSOLE DASHBOARD
# ==============================================================================

cat("\n")
cat("======================================================================\n")
cat("SUPPLEMENTARY FIGURE S3 UNIFIED-BURDEN FINAL COMPLETED\n")
cat("======================================================================\n")

cat("\nPANEL A -- SEVERE VS ALL NON-SEVERE\n")
print(
  plot_dt[
    panel ==
      PANEL_A,
    .(
      cohort,
      effect,
      CI_low,
      CI_high,
      I2
    )
  ]
)

cat("\nPANEL B -- STRICT >=2 ADL/IADL DETERIORATION\n")
print(
  plot_dt[
    panel ==
      PANEL_B,
    .(
      cohort,
      effect,
      CI_low,
      CI_high,
      I2
    )
  ]
)

cat("\nINTERPRETATION GUARDRAILS\n")
cat("- Source: Script 31 unified-burden sensitivity analysis.\n")
cat("- Panel A is an alternative severe-endpoint definition.\n")
cat("- Panel B is a stricter supportive deterioration endpoint.\n")
cat("- The >=2-item analysis has substantial between-cohort heterogeneity and should be described accordingly.\n")
cat("- Neither analysis replaces the primary transition-severity analysis.\n")

cat("\nOUTPUT FILES\n")
cat("PNG    : ", OUT_PNG, "\n", sep = "")
cat("PDF    : ", OUT_PDF, "\n", sep = "")
cat("TIFF   : ", OUT_TIFF, "\n", sep = "")
cat("DATA   : ", OUT_DATA, "\n", sep = "")
cat("CAPTION: ", OUT_CAPTION, "\n", sep = "")

cat("\nFINAL STATUS: PASS\n")
cat("======================================================================\n")
